name: Update README with latest blog posts

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:        # Lets you trigger it manually

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update README with latest posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://geekcircuit.com/feed/"
