name: Update README with latest blog posts

on:
  schedule:
    - cron: '0 */12 * * *'  # runs every 12 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"

      - name: Update README with latest posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://geekcircuit.com/feed/"

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated with the latest blog posts"
          branch: main
          commit_user_name: GitHub Action
          commit_user_email: actions@github.com
          repository: jaikrishnatavva/jaikrishnatavva
          github_token: ${{ secrets.GH_PAT }}
